/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class JFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame.class.getName());

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        pnlcentral = new javax.swing.JPanel();
        pnlconversor = new javax.swing.JPanel();
        lblconversor = new javax.swing.JLabel();
        lblpedido = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        rbtnFahrenheit = new javax.swing.JRadioButton();
        rbtnCelcius = new javax.swing.JRadioButton();
        rbtnKelvin = new javax.swing.JRadioButton();
        rbtnRadianes = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 2 - De Celcius a Farenheit");

        pnlcentral.setBackground(new java.awt.Color(204, 204, 204));

        lblconversor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblconversor.setText("Conversor de Temperatura");

        javax.swing.GroupLayout pnlconversorLayout = new javax.swing.GroupLayout(pnlconversor);
        pnlconversor.setLayout(pnlconversorLayout);
        pnlconversorLayout.setHorizontalGroup(
            pnlconversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlconversorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblconversor)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlconversorLayout.setVerticalGroup(
            pnlconversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlconversorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblconversor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblpedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblpedido.setText("Ingrese temperatura en Grados");

        btnConvertir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/icons8-aprobar-y-actualizar-48.png"))); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(this::btnConvertirActionPerformed);

        buttonGroup1.add(rbtnFahrenheit);
        rbtnFahrenheit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnFahrenheit.setText("A Fahrenheit");

        buttonGroup1.add(rbtnCelcius);
        rbtnCelcius.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnCelcius.setText("A Celcius");

        buttonGroup1.add(rbtnKelvin);
        rbtnKelvin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnKelvin.setText("A Kelvin");
        rbtnKelvin.addActionListener(this::rbtnKelvinActionPerformed);

        buttonGroup1.add(rbtnRadianes);
        rbtnRadianes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnRadianes.setText("A Radianes");

        javax.swing.GroupLayout pnlcentralLayout = new javax.swing.GroupLayout(pnlcentral);
        pnlcentral.setLayout(pnlcentralLayout);
        pnlcentralLayout.setHorizontalGroup(
            pnlcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcentralLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcentralLayout.createSequentialGroup()
                        .addComponent(txtingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcentralLayout.createSequentialGroup()
                        .addGroup(pnlcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlcentralLayout.createSequentialGroup()
                                .addComponent(rbtnFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnlconversor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblpedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlcentralLayout.createSequentialGroup()
                                .addComponent(rbtnKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnRadianes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
            .addGroup(pnlcentralLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlcentralLayout.setVerticalGroup(
            pnlcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcentralLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlconversor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblpedido)
                .addGap(18, 18, 18)
                .addComponent(txtingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFahrenheit)
                    .addComponent(rbtnCelcius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnKelvin)
                    .addComponent(rbtnRadianes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnConvertir)
                .addGap(7, 7, 7))
        );

        jDesktopPane1.setLayer(pnlcentral, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(pnlcentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlcentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void rbtnKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnKelvinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblconversor;
    private javax.swing.JLabel lblpedido;
    private javax.swing.JPanel pnlcentral;
    private javax.swing.JPanel pnlconversor;
    private javax.swing.JRadioButton rbtnCelcius;
    private javax.swing.JRadioButton rbtnFahrenheit;
    private javax.swing.JRadioButton rbtnKelvin;
    private javax.swing.JRadioButton rbtnRadianes;
    private javax.swing.JTextField txtingreso;
    // End of variables declaration//GEN-END:variables
}
